#include "sqlextern.ch"

REQUEST SQLRDD
REQUEST SR_FIREBIRD
REQUEST SR_FIREBIRD3
REQUEST SR_FIREBIRD4
REQUEST SR_FIREBIRD5
REQUEST SR_MYSQL
REQUEST SR_PGS
REQUEST SR_ODBC
REQUEST SR_ORACLE

FUNCTION Main()
RETURN NIL
