#include "sqlextern.ch"

REQUEST SQLRDD
REQUEST SR_FIREBIRD
REQUEST SR_FIREBIRD3
REQUEST SR_FIREBIRD4
REQUEST SR_FIREBIRD5
REQUEST SR_MARIA
REQUEST SR_MYSQL
REQUEST SR_ODBC
REQUEST SR_ORACLE
REQUEST SR_ORACLE2
REQUEST SR_PGS
REQUEST sr_TXMLDocument

FUNCTION Main()
RETURN NIL
